### ISSUE TITLE
Create initial UI and layout propositions

### ISSUE THREAD

**Issue by maximiseuk** [maximiseuk/onlinestudytools#10]
### We need a basic layout for the web app.
This doesn't really need any branding or colours or fancy graphics, I'm talking more about the actual layout - something you would be able to sketch on a piece of paper. For example, this is more about the position and size of each button than the colour, font and hover effect of each button.

Something like this would be great (it's meant to be in greyscale):

![image](https://user-images.githubusercontent.com/58519535/70470791-c0929c00-1ac3-11ea-9b76-435e7bf83ba7.png)

It doesn't have any images, themes or any real affiliation with a UI framework. It is generic. 

### Here are the requirements for this task:
 - [ ] Create a routing structure or sitemap
 - [ ] Finalise what content each page should have on it
 - [ ] Create a wire-frame mockup (just for the layout) of each page, as in the image above

**This task does not involve any coding - the wireframe is an image or vector graphic.**

I'm going to be working on this task. *If you want to work on it with me, add yourself as an assignee*. We can share files and ideas on Discord.

**Comment by Joseph-Rance** [comment]
Ok so I think we have some updated tasks to do:

- [ ] decide on whether we will use the design put forward by me
- [ ] remove yellow from the design
- [ ] make card templates for manufacturing so we have a consistent design
- [ ] update the wire frame so the layout supports slightly larger dashboards for each tool
