### ISSUE TITLE
Finish all website UI

### ISSUE THREAD

**Issue by maximiseuk** [maximiseuk/onlinestudytools#25]
This is obviously a really big task, and I understand that there's a lot of pressure on @isaacholt100  but we need the entire UI to be finished ASAP, including all the parts of the website that have been previously discussed.

This includes:
 - [ ] Landing page
 - [x] Login and Sign up pages
 - [x] Main dashboard
 - [x] Settings
 - [x] All tools sections
 - [x] Probably other things that I've forgotten about

@isaacholt100 Ideally the deadline for this work is probably around Wednesday next week (01/01/20) and I know that is not a long time, so please ask for help if you need it! I'm currently working on the server, getting login and sign up functionality ready, but I am prepared to help with the website if you need me to. 

The reasoning behind that deadline is that I don't really want to leave everything to the last minute; we'll want at least a week to pull everything together, getting the server working with the front-end, getting the hosting and domain ready, integrating the machine learning stuff and testing the whole service.

**Comment by Joseph-Rance** [comment]
Some changes to do:
 - light theme should turn on when the switch is flicked without clicking save.
 - borders at the home screen
 - add ml interfaces
 - add landing page

**Comment by Joseph-Rance** [comment]
Only waiting for the landing page here and that has its own issue so I'm closing this one
