### ISSUE TITLE
Is the webapp-structure branch still required?

### ISSUE THREAD

**Issue by maximiseuk** [maximiseuk/onlinestudytools#30]
It hasn't been used in ages. Can we delete it?

**Comment by Joseph-Rance** [comment]
No, I don't think so. I think it is safe to delete but if u want to be careful, I'd wait for Isaac to reply first as he is the one that made it.

**Comment by Joseph-Rance** [comment]
He said he doesn't need it anymore

**Comment by Joseph-Rance** [comment]
I closed this issue BC I was gonna delete the branch but apparently that's not possible on phone so I'll do it tomorrow.
