### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by Joseph-Rance** [maximiseuk/onlinestudytools#43]
So these are the things that I have identified to change to improve SEO (I'll update this list as I learn more about it):
 - change our webpage title to "maximise - study tools by students" or something more descriptive - will look at which search terms get the most searched to really get the right phrasing.
 - change our description to something that shows out USPs more (tech and science etc) but also stuf people search for. Maybe it would be worth looking at what sites like *Seneca* do for this
 - get links to our websites from other sites *with content*, like blogs. We should try to do some collaborations or something to get this done.
 - getting articles onto our website. Maybe having somewhere on the landing page that links to a blog, where we can have interviews with that scientist person etc.. That will really get some text content on our website and do us a lot of good. Also, doing articles on the science of revising highlights out USPs more.

@KashParty do u know how I can edit the description for the page on google? I can't do it in ecowebhosting (or i'm blind) and I don't have access to any of our other accounts so I can't really do that without ur help/

**Comment by Joseph-Rance** [comment]
For example, getting onto one of these sorts of lists (https://www.collegeraptor.com/find-colleges/articles/tips-tools-advice/10-free-online-study-tools/) would do us a lot of good for SEO. I'm sure we can find some way to get onto one.

**Comment by maximiseuk** [comment]
> @KashParty do u know how I can edit the description for the page on google? I can't do it in ecowebhosting (or i'm blind) and I don't have access to any of our other accounts so I can't really do that without ur help/

I think it might be an HTML meta tag?

**Comment by Joseph-Rance** [comment]
Yes thanks. I'm adding them now, but I don't know how to test them... so hope i guess?

**Comment by Joseph-Rance** [comment]
I'v been looking around and I think these are the main searches we should be targeting:

| term                     	| Searches (/month) 	|
|--------------------------	|-------------------	|
| Revision Apps            	| 1300              	|
| Apps For Studying        	| 720               	|
| GCSE Revision Flashcards 	| 210               	|
| GCSE Revision Tips       	| 480               	|
| GCSE Revision Timetable  	| 1600              	|

So I added this to the head:
```
<title> Maximise – GCSE revision app</title>
<meta name=”description” content=” Maximise uses technology such as machine learning to create personalised GCSE revision timetables as well as having revision tips from top students and more!”>
<meta name=”keywords” content=”Revision apps, apps for studying, GCSEs, revision, GCSE revision flashcards, revision tips, GCSE revision tips, GCSE, Revision app, GCSE Revision Tips, Revision Timetable, Revision Template, Revision Timetable Template, GCSE Revision Timetable, GCSE Revision Template, GCSE Revision Timetable Template”>
```

**Comment by Joseph-Rance** [comment]
This text here sort of sums up what needs to be done:
![image](https://user-images.githubusercontent.com/56409230/74677256-b8d03180-51af-11ea-87ec-aa44ac67dc7f.png)

So we gonna get a new revised SEO plan

**Comment by Joseph-Rance** [comment]
1. We need to keep people on our site for as long as possible, for higher rankings (and stuff like looking at timetable doesn't really do that) so I'm thinking we get an interview done with that scientist person about studying efficiently to put on the site, so people spend time reading on our site reducing bounce rate and increasing visit durations
2. add meta to all pages
3. improve images (eg adding keywords to them). Useful: https://www.quicksprout.com/the-advance-guide-to-seo-for-images/
4. add links to good sites Like BBC bitesize onto some of the pages
![image](https://user-images.githubusercontent.com/56409230/74677594-aa364a00-51b0-11ea-834a-62033b70955a.png)
5. we should put some sort of contact us on the landing page:
![image](https://user-images.githubusercontent.com/56409230/74677670-dfdb3300-51b0-11ea-9142-e2f0fa7eafc1.png)
6. get links to maximise on social media (on our accounts and push hard to share them)
![image](https://user-images.githubusercontent.com/56409230/74677714-04cfa600-51b1-11ea-8a5f-b7105671170a.png)

**Comment by Joseph-Rance** [comment]
@KashParty  I ran a CEO checker and it pointed this out. Is it possible to get at least one of these onto the page?
![image](https://user-images.githubusercontent.com/56409230/74689799-68b79600-51d4-11ea-9a0c-761c9f3f4062.png)

**Comment by Joseph-Rance** [comment]
can see our report here: https://flauntdigital.com/free-seo-analysis-report/?url=maximise.org.uk

**Comment by Joseph-Rance** [comment]
@KashParty If u can be bothered, these are the images google search console thinks should be smaller:
![image](https://user-images.githubusercontent.com/56409230/75044808-2636d780-54ba-11ea-98da-03a2ad19b6d7.png)

**Comment by Joseph-Rance** [comment]
I've signed into both search console and analytics, but I need the site to be put onto maximise.org.uk now because I can't use it until the tag is on index.html. @maximiseuk When would it be possible to do that?

**Comment by Joseph-Rance** [comment]
It would be good if we had some links to other sites from our site, so I compiled a list of sites that we could link to and their number of good backlinks:

```
https://www.cgpbooks.co.uk/					524
https://quizlet.com/						0
https://www.bbc.co.uk/bitesize					226700
https://www.freesciencelessons.co.uk/				48
https://www.senecalearning.com/					216
http://www.gojimo.com/						136
https://www.tes.com/teaching-resources/gcse-exam-revision	6200
```

**Comment by Joseph-Rance** [comment]
ok so most of the small things are done for the SEO (some things are still in prs tho), with the only thing left being the interview, which will not be done for a while. If @maximiseuk could accept my prs tho that would be helpful because at the moment none of my commits are actually in master (and i've just been doing prs straight to master bc there are only a few changes for each pr so there is no point making a separate seo branch)

**Comment by Joseph-Rance** [comment]
ok all that is needed is the backlinks and I have no long term plans for so I'm closing this issue
